<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnLogo</name>
   <tag></tag>
   <elementGuidId>dfc93ee5-e812-4491-a421-98b84a4b6d76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>.//img[@class=&quot;katalon-logo&quot;]/@src</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
